spring.application.name=pulse-social
spring.datasource.url=jdbc:postgresql://ep-silent-silence-a1vwtvoo-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vLDwW2TlyQ6H
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.keys.private=file:./config/keys/private_key.pem
jwt.keys.public=file:./config/keys/public_key.pem
jwt.access-token.expiry-minutes=15
